server:
  port: 8086
  max-http-header-size: 64KB
spring:
  application:
    name: cf-chat-api
  profiles:
    active: dev
  redis:
    host: redis_host
    port: 6379
    password: redis_password
    database: 0
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
auth:
  tokenValiditySeconds: 1200
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: xuecheng.com
  cookieMaxAge: -1

