#默认使用配置
spring:
  profiles:
    active: dev
  datasource:
    name: caifeng
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mysql_host:3306/caifeng?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: mysql_user_name
    password: mysql_user_password
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 32

#公共配置与profiles选择无关
mybatis:
#  mapperScanPackage: com.cf.mapper
#  typeAliasesPackage: com.cf.pojo
  mapperLocations: classpath:com.cf.ucenter.dao.mapper/*.xml
  configLocation: classpath:config/SqlMapConfig.xml

