server:
  port: 8091
  max-http-header-size: 64KB
spring:
  application:
    name: cf-ucenter-admin
  profiles:
    active: dev
  datasource:
    name: caifeng
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mysql_host:3306/caifeng?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: mysql_user_name
    password: mysql_user_password
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 32
  redis:
    host: redis_host
    port: 6379
    password: redis_password
    database: 0
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
auth:
  tokenValiditySeconds: 1200
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: xuecheng.com
  cookieMaxAge: -1

